[package]
name = "ray-tracing-one-weekend"
version = "0.1.0"
authors = ["safarte <bchichereau@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
image = "0.23.14"
rayon = "1.0.3"
